//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLSigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLSigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.windows.com
        ///time.google.com
        ///time.cloudflare.com
        ///time.facebook.com
        ///time.apple.com
        ///time-a-g.nist.gov
        ///ntp1.stratum1.ru
        ///ntp.ru
        ///ntp.gsu.edu
        ///ntp.nsu.ru
        ///ntp.nict.jp.
        /// </summary>
        internal static string NtpServerList {
            get {
                return ResourceManager.GetString("NtpServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://timestamp.globalsign.com/scripts/timstamp.dll
        ///https://timestamp.geotrust.com/tsa
        ///http://timestamp.comodoca.com/rfc3161
        ///http://timestamp.wosign.com
        ///http://tsa.startssl.com/rfc3161
        ///http://time.certum.pl
        ///http://timestamp.digicert.com
        ///https://freetsa.org
        ///http://dse200.ncipher.com/TSS/HttpTspServer
        ///http://tsa.safecreative.org
        ///http://zeitstempel.dfn.de
        ///https://ca.signfiles.com/tsa/get.aspx
        ///http://services.globaltrustfinder.com/adss/tsa
        ///https://tsp.iaik.tugraz.at/tsp/TspRequest
        ///http://timestam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TsaServerList {
            get {
                return ResourceManager.GetString("TsaServerList", resourceCulture);
            }
        }
    }
}
